NUMBER_OF_PERIODS = 2
MINUTES_PER_PERIOD = 20
MINUTES_PER_HALF = MINUTES_PER_PERIOD / (NUMBER_OF_PERIODS / 2)
CLOCK_INTERVAL = 12
TIMEOUTS_PER_PERIOD = 3
MAX_MOMENTUM = 5
MIN_MOMENTUM = -5
FOULS_FOR_BONUS = 7
FOULS_FOR_DOUBLE_BONUS = 10
PERSONAL_FOULS_PER_GAME = 5

Positions = ["PG", "SG", "SF", "PF", "C"]